### ISSUE TITLE
unresolved import wlc

### ISSUE THREAD

**Issue by edvorg** [Drakulix/wlc#5]
Hi, trying to add your crate to dependencies, but can't import it.
Tried all three ways
>Add to your Cargo.toml
>wlc = "0.1"
>For stable
>wlc = { version = "1.0", features = "unsafe-stable" }
>For static compilation (combination is possible)
>wlc = { version = "1.0", features = "static" }

**Comment by edvorg** [comment]
```
[edvorg@edvorg-manjaro ~]$ rustc --version                                      
rustc 1.25.0-nightly (97520ccb1 2018-01-21)                                     
[edvorg@edvorg-manjaro ~]$ cargo --version                                      
cargo 0.26.0-nightly (6a8eb71f6 2018-01-13)
```

**Comment by Drakulix** [comment]
Hey, first of all this is no longer maintained (I should probably put a note somewhere) as I am using https://github.com/Smithay/smithay for the purpose of this library now and `wlc` itself is discontinued.

However your error clearly indicates, that you don't have wlc itself installed (it is a C library, you need to provide the dependency yourself, cargo cannot do this for you).

For installation instructions see [`wlc`'s project page](https://github.com/Cloudef/wlc)

**Comment by edvorg** [comment]
Hi, thank you! I'll take a look
